language: android
before_install:
     - chmod +x gradlew
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-26
    - build-tools-26.1.4
    
# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

notifications:
  email: false
