language: android
before_install:
     - chmod +x gradlew
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-26
    - build-tools-26.1.4
    
sudo: false
 "os": "windows"
